apiVersion: v1
kind: Service
metadata:
  name: pos-app-service
spec:
  selector:
    app: pos
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30007
